version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/srv/src
      - ./data:/data
      - ./var/cache:/srv/var/cache
    env_file:
      - .env
    depends_on:
      - mock

  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "8080:80"
    volumes:
      - ./mock_data:/srv
